---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier
- name: version

outputs:
- name: aqueduct-binaries
- name: artifacts-for-docker-image

run:
  path: go/src/github.com/pivotal-cf/aqueduct-courier/ci/tasks/build-binaries

params:
  DATA_LOADER_URL:
