---
platform: windows

inputs:
- name: binary
- name: ci

outputs:
- name: collected-data

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/ci/tasks/collect-windows.ps1

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  OPS_MANAGER_TIMEOUT:
  ENV_TYPE:
  FOUNDATION_NICKNAME:
  INSECURE_SKIP_TLS_VERIFY:
  WITH_CREDHUB_INFO:
  CF_API_URL:
  USAGE_SERVICE_URL:
  USAGE_SERVICE_CLIENT_ID:
  USAGE_SERVICE_CLIENT_SECRET:
  USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY:
