---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: aqueduct-courier
- name: binaries

outputs:
- name: collected-data

run:
  path: aqueduct-courier/ci/tasks/collect

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  ENV_TYPE:
