---
platform: linux

inputs:
- name: binary

outputs:
- name: collected-data

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    chmod +x ./binary/insights-collector-linux-amd64
    ./binary/insights-collector-linux-amd64 --version
    ./binary/insights-collector-linux-amd64 collect --output-dir ./collected-data --insecure-skip-tls-verify

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  ENV_TYPE:
