---
platform: linux

inputs:
- name: binary

outputs:
- name: collected-data

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    chmod +x ./binary/telemetry-collector-linux-amd64
    ./binary/telemetry-collector-linux-amd64 --version

    skip_tls_verify_arg=$([ -z "$INSECURE_SKIP_TLS_VERIFY" ] && echo "" || echo "--insecure-skip-tls-verify")
    ./binary/telemetry-collector-linux-amd64 collect --output-dir ./collected-data "${skip_tls_verify_arg}"

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  ENV_TYPE:
  INSECURE_SKIP_TLS_VERIFY:
