---
platform: linux

inputs:
- name: binary

outputs:
- name: collected-data

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    chmod +x ./binary/telemetry-collector-linux-amd64
    ./binary/telemetry-collector-linux-amd64 --version

    ./binary/telemetry-collector-linux-amd64 collect --output-dir ./collected-data"

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  OPS_MANAGER_TIMEOUT:
  ENV_TYPE:
  INSECURE_SKIP_TLS_VERIFY:
  WITH_CREDHUB_INFO:
  CF_API_URL:
  USAGE_SERVICE_URL:
  USAGE_SERVICE_CLIENT_ID:
  USAGE_SERVICE_CLIENT_SECRET:
  USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY:
