---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: binaries

outputs:
- name: collected-data

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    tar xvf binaries/*.tgz
    ./aqueduct-linux-amd64 --version
    ./aqueduct-linux-amd64 collect --output-dir ./collected-data --insecure-skip-tls-verify

params:
  OPS_MANAGER_URL:
  OPS_MANAGER_USERNAME:
  OPS_MANAGER_PASSWORD:
  OPS_MANAGER_CLIENT_ID:
  OPS_MANAGER_CLIENT_SECRET:
  ENV_TYPE:
