---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier

run:
  path: go/src/github.com/pivotal-cf/aqueduct-courier/ci/tasks/courier-tests
