---
platform: windows

inputs:
- name: aqueduct-courier
  path: go/src/github.com/pivotal-cf/aqueduct-courier
- name: ci

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/ci/tasks/courier-tests.ps1
