---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: platforminsightsteam/aqueduct-staging
    tag: latest

outputs:
- name: package-receipt

run:
  path: /bin/bash
  args:
   - -c
   - 'dpkg -l > package-receipt/docker-image-package-receipt'

