---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: aqueduct-courier
- name: binaries
- name: collected-data

run:
  path: aqueduct-courier/ci/tasks/send

params:
  API_KEY:
