---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: binaries
- name: collected-data

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    tar xvf binaries/*.tgz
    ./platform-insights-collector-linux-amd64 --version
    ./platform-insights-collector-linux-amd64 send --path ./collected-data/*.tar

params:
  API_KEY:
