---
platform: windows

inputs:
- name: binary
- name: collected-data
- name: ci

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/ci/tasks/send-windows.ps1

params:
  API_KEY:
