---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: platforminsightsteam/aqueduct-staging
    tag: latest

inputs:
- name: aqueduct-courier
- name: collected-data

run:
  path: aqueduct-courier/ci/tasks/send

params:
  API_KEY:
