---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: version

outputs:
- name: metadata

run:
  path: sh
  args:
  - -c
  - |
    #!/bin/bash

    set -xe

    cat << PIVNET_METADATA > metadata/metadata
    ---
    release:
      version: "$(cat version/version)"
      eula_slug: "pivotal_software_eula"
      release_type: "Alpha Release"
      availability: Selected User Groups Only
      eccn: "EAR99"
    PIVNET_METADATA
