resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
- name: aqueduct-courier
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/aqueduct-courier
    private_key: {{courier-git-deploy-private-key}}
- name: staging-binaries
  type: gcs-resource
  source:
    bucket: {{courier-staging-builds-bucket}}
    json_key: {{courier-gcp-service-account-key}}
    versioned_file: aqueduct-cli.tgz

jobs:
- name: courier-tests
  serial_groups: [opsmanager-lock]
  plan:
  - get: aqueduct-courier
    trigger: true
  - task: run-tests
    file: aqueduct-courier/ci/tasks/courier-tests.yml
    params:
      TEST_OPS_MANAGER_URL: {{courier-ops-manager-url}}
      TEST_OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      TEST_OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}
      TEST_OPS_MANAGER_CLIENT_ID: {{courier-ops-manager-client-id}}
      TEST_OPS_MANAGER_CLIENT_SECRET: {{courier-ops-manager-client-secret}}

- name: windows-courier-tests
  serial_groups: [opsmanager-lock]
  plan:
  - get: aqueduct-courier
    trigger: true
  - task: run-tests
    file: aqueduct-courier/ci/tasks/courier-tests-windows.yml
    params:
      TEST_OPS_MANAGER_URL: {{courier-ops-manager-url}}
      TEST_OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      TEST_OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}
      TEST_OPS_MANAGER_CLIENT_ID: {{courier-ops-manager-client-id}}
      TEST_OPS_MANAGER_CLIENT_SECRET: {{courier-ops-manager-client-secret}}

- name: build-staging-binaries
  plan:
  - get: aqueduct-courier
    passed: [courier-tests, windows-courier-tests]
    trigger: true
  - task: build-binaries
    file: aqueduct-courier/ci/tasks/build-binaries.yml
    params:
      DATA_LOADER_URL: {{staging-data-loader-url}}
  - put: staging-binaries
    params:
      file: aqueduct-binaries/aqueduct-cli.tgz

- name: test-collect-and-send
  plan:
  - get: aqueduct-courier
    passed: [build-staging-binaries]
    trigger: true
  - get: staging-binaries
    passed: [build-staging-binaries]
  - task: collect-and-send
    input_mapping:
      binaries: staging-binaries
    file: aqueduct-courier/ci/tasks/collect-and-send.yml
    params:
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}
      API_KEY: {{loader-api-key}}
