resource_types:
  - name: gcs-resource
    type: registry-image
    source:
      repository: frodenas/gcs-resource
  - name: pivnet
    type: registry-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: latest-final
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: pivotal-telemetry-collector
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: pivotal-telemetry-collector
    release_type: Alpha Release
    copy_metadata: true
- name: aqueduct-courier
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/aqueduct-courier
    private_key: {{courier-git-deploy-private-key}}
    ignore_paths: [ci]
- name: lts-aqueduct-courier
  type: git
  source:
    branch: {{lts_branch_name}}
    uri: git@github.com:pivotal-cf/aqueduct-courier
    private_key: {{courier-git-deploy-private-key}}
    ignore_paths: [ci]
- name: ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/aqueduct-courier
    private_key: {{courier-git-deploy-private-key}}
    paths: [ci]
- name: staging-binaries
  type: gcs-resource
  source:
    bucket: {{courier-staging-builds-bucket}}
    json_key: {{courier-gcp-service-account-key}}
    regexp: aqueduct-cli-(.*).tgz
- name: staging-linux-binary
  type: gcs-resource
  source:
    bucket: {{courier-staging-builds-bucket}}
    json_key: {{courier-gcp-service-account-key}}
    versioned_file: telemetry-collector-linux-amd64
- name: production-binaries
  type: gcs-resource
  source:
    bucket: {{courier-production-builds-bucket}}
    json_key: {{courier-gcp-service-account-key}}
    regexp: aqueduct-cli-(.*).tgz
- name: production-linux-binary
  type: gcs-resource
  source:
    bucket: {{courier-production-builds-bucket}}
    json_key: {{courier-gcp-service-account-key}}
    versioned_file: telemetry-collector-linux-amd64
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/aqueduct-courier
    branch: version
    file: VERSION
    private_key: {{courier-git-deploy-private-key}}
- name: collection-timer
  type: time
  source:
    interval: 1h
- name: prod-collection-timer
  type: time
  source:
    interval: 10m
- name: task-docker-image
  type: registry-image
  source:
    repository: ubuntu
    tag: xenial
- name: prod-slack-notification
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

jobs:
- name: courier-tests
  serial_groups: [courier-tests]
  plan:
  - get: aqueduct-courier
    trigger: true
  - get: ci
  - task: run-tests
    file: ci/ci/tasks/courier-tests.yml

- name: windows-courier-tests
  serial_groups: [windows-courier-tests]
  plan:
  - get: aqueduct-courier
    trigger: true
  - get: ci
  - task: run-tests
    file: ci/ci/tasks/courier-tests-windows.yml

- name: build-staging-binaries
  serial_groups: [version]
  plan:
  - aggregate:
    - get: aqueduct-courier
      passed: [courier-tests, windows-courier-tests]
      trigger: true
    - get: version
      params: {pre: build}
    - get: ci
  - task: build-binaries
    file: ci/ci/tasks/build-binaries.yml
    params:
      DATA_LOADER_URL: {{staging-data-loader-url}}
  - put: staging-binaries
    params:
      file: aqueduct-binaries/aqueduct-cli-*.tgz
  - put: staging-linux-binary
    params:
      file: linux-binary/*linux*
  - put: version
    params: {file: version/version}

- name: test-collect-credhub-info
  plan:
  - aggregate:
    - get: version
      passed: [build-staging-binaries]
    - get: aqueduct-courier
      passed: [build-staging-binaries]
      trigger: true
    - get: staging-linux-binary
      passed: [build-staging-binaries]
    - get: ci
  - task: collect-credhub-info
    file: ci/ci/tasks/collect-with-credhub-info.yml
    input_mapping:
      binary: staging-linux-binary
    params:
      GCP_SERVICE_ACCOUNT_KEY: {{courier-gcp-service-account-key}}
      GCP_PROJECT_ID: {{courier-gcp-project-id}}
      GCP_INSTANCE_NAME: {{courier-opsman-gcp-instance-name}}
      GCP_ZONE: {{courier-gcp-zone}}
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}

- name: test-collect-and-send
  plan:
  - aggregate:
    - get: version
      passed: [build-staging-binaries]
    - get: collection-timer
      trigger: true
    - get: aqueduct-courier
      passed: [build-staging-binaries]
      trigger: true
    - get: staging-linux-binary
      passed: [build-staging-binaries]
    - get: task-docker-image
    - get: ci
  - task: collect-with-opsmanager-user-creds
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    file: ci/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{courier-cf-api-url}}
      USAGE_SERVICE_URL: {{courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: collect-with-opsmanager-client-creds
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    output_mapping:
      collected-data: collected-data-with-client-creds
    file: ci/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_CLIENT_ID: {{courier-ops-manager-client-id}}
      OPS_MANAGER_CLIENT_SECRET: {{courier-ops-manager-client-secret}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{courier-cf-api-url}}
      USAGE_SERVICE_URL: {{courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: send
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    file: ci/ci/tasks/send.yml
    params:
      API_KEY: {{loader-api-key}}

- name: build-production-binaries
  serial_groups: [version]
  plan:
  - aggregate:
    - get: aqueduct-courier
      passed: [test-collect-and-send, test-collect-credhub-info]
    - get: version
      params: {bump: final}
      passed: [test-collect-and-send, test-collect-credhub-info]
    - get: ci
  - put: aqueduct-courier
    params:
      repository: aqueduct-courier
      tag: version/version
      only_tag: true
  - task: build-binaries
    file: ci/ci/tasks/build-binaries.yml
    params:
      DATA_LOADER_URL: {{production-data-loader-url}}
      ENSURE_HTTPS: true
  - put: production-binaries
    params:
      file: aqueduct-binaries/aqueduct-cli-*.tgz
  - put: production-linux-binary
    params:
      file: linux-binary/*linux*
  - put: version
    params: {file: version/version}

- name: auto-patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [build-production-binaries]
    params: {bump: patch, pre: build}
    trigger: true
  - put: version
    params: {file: version/version}

- name: test-collect-and-send-production
  plan:
  - aggregate:
    - get: aqueduct-courier
      passed: [build-production-binaries]
      trigger: true
    - get: production-binaries
      passed: [build-production-binaries]
    - get: production-linux-binary
      passed: [build-production-binaries]
    - get: task-docker-image
    - get: ci
  - task: collect-with-opsmanager-user-creds
    image: task-docker-image
    input_mapping:
      binary: production-linux-binary
    file: ci/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{production-courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{production-courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{production-courier-ops-manager-password}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{production-courier-cf-api-url}}
      USAGE_SERVICE_URL: {{production-courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{production-courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{production-courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: send
    image: task-docker-image
    input_mapping:
      binary: production-linux-binary
    file: ci/ci/tasks/send.yml
    params:
      API_KEY: {{production-loader-api-key}}

- name: release-to-pivnet
  plan:
  - aggregate:
    - get: aqueduct-courier
      passed: [test-collect-and-send-production]
      trigger: true
    - get: production-binaries
      passed: [test-collect-and-send-production]
    - get: version
      passed: [build-production-binaries]
    - get: ci
  - task: prepare-release-files
    file: ci/ci/tasks/prep-release-files.yml
    input_mapping:
      binaries-tar: production-binaries
  - task: write-metadata
    file: ci/ci/tasks/write-metadata.yml
  - put: pivotal-telemetry-collector
    params:
      file_glob: release-files/*
      metadata_file: metadata/metadata

- name: major
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: build}
  - put: version
    params: {file: version/version}

- name: minor
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: build}
  - put: version
    params: {file: version/version}

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch, pre: build}
  - put: version
    params: {file: version/version}

- name: ensure-production-sends
  plan:
  - aggregate:
    - get: pivotal-telemetry-collector
      params:
        globs: ["telemetry-collector-linux-amd64*"]
    - get: prod-collection-timer
      trigger: true
    - get: aqueduct-courier
    - get: task-docker-image
    - get: ci
  - task: strip-collector-version
    image: task-docker-image
    file: ci/ci/tasks/strip-collector-version.yml
    input_mapping:
      binary-with-version: pivotal-telemetry-collector
  - task: collect
    image: task-docker-image
    file: ci/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{production-courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{production-courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{production-courier-ops-manager-password}}
      CF_API_URL: {{production-courier-cf-api-url}}
      USAGE_SERVICE_URL: {{production-courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{production-courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{production-courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
  - task: send
    image: task-docker-image
    file: ci/ci/tasks/send.yml
    params:
      API_KEY: {{production-loader-api-key}}
    on_failure:
      put: prod-slack-notification
      params:
        text: |
          Failed to send OpsManager dataset to production. Build: https://wings.pivotal.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

############################ LTS
- name: lts-courier-tests
  serial_groups: [courier-tests]
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      trigger: true
    - get: ci
  - task: run-tests
    file: ci/ci/tasks/courier-tests.yml

- name: lts-windows-courier-tests
  serial_groups: [windows-courier-tests]
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      trigger: true
    - get: ci
  - task: run-tests
    file: ci/ci/tasks/courier-tests-windows.yml

- name: lts-build-staging-binaries
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-courier-tests, lts-windows-courier-tests]
      trigger: true
    - get: ci
  - task: generate-version-file
    file: ci/ci/tasks/generate-version-file.yml
    params:
      VERSION: {{lts_version}}
  - task: build-binaries
    file: ci/ci/tasks/build-binaries.yml
    params:
      DATA_LOADER_URL: {{staging-data-loader-url}}
  - put: staging-binaries
    params:
      file: aqueduct-binaries/aqueduct-cli-*.tgz
  - put: staging-linux-binary
    params:
      file: linux-binary/*linux*

- name: lts-test-collect-credhub-info
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-build-staging-binaries]
      trigger: true
    - get: staging-linux-binary
      passed: [lts-build-staging-binaries]
    - get: ci
  - task: collect-credhub-info
    file: ci/ci/tasks/collect-with-credhub-info.yml
    input_mapping:
      binary: staging-linux-binary
    params:
      GCP_SERVICE_ACCOUNT_KEY: {{courier-gcp-service-account-key}}
      GCP_PROJECT_ID: {{courier-gcp-project-id}}
      GCP_INSTANCE_NAME: {{courier-opsman-gcp-instance-name}}
      GCP_ZONE: {{courier-gcp-zone}}
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}

- name: lts-test-collect-and-send
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-build-staging-binaries]
      trigger: true
    - get: staging-linux-binary
      passed: [lts-build-staging-binaries]
    - get: task-docker-image
    - get: ci
  - task: collect-with-opsmanager-user-creds
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    # Using branch's ci instead of master's due to task differences
    file: aqueduct-courier/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{courier-ops-manager-password}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{courier-cf-api-url}}
      USAGE_SERVICE_URL: {{courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: collect-with-opsmanager-client-creds
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    output_mapping:
      collected-data: collected-data-with-client-creds
    # Using branch's ci instead of master's due to task differences
    file: aqueduct-courier/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{courier-ops-manager-url}}
      OPS_MANAGER_CLIENT_ID: {{courier-ops-manager-client-id}}
      OPS_MANAGER_CLIENT_SECRET: {{courier-ops-manager-client-secret}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{courier-cf-api-url}}
      USAGE_SERVICE_URL: {{courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: send
    image: task-docker-image
    input_mapping:
      binary: staging-linux-binary
    file: ci/ci/tasks/send.yml
    params:
      API_KEY: {{loader-api-key}}

- name: lts-build-production-binaries
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-test-collect-and-send, lts-test-collect-credhub-info]
    - get: ci
  - task: generate-version-file
    file: ci/ci/tasks/generate-version-file.yml
    params:
      VERSION: {{lts_version}}
  - put: lts-aqueduct-courier
    params:
      repository: aqueduct-courier
      tag: version/version
      only_tag: true
  - task: build-binaries
    file: ci/ci/tasks/build-binaries.yml
    params:
      DATA_LOADER_URL: {{production-data-loader-url}}
      ENSURE_HTTPS: true
  - put: production-binaries
    params:
      file: aqueduct-binaries/aqueduct-cli-*.tgz
  - put: production-linux-binary
    params:
      file: linux-binary/*linux*

- name: lts-test-collect-and-send-production
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-build-production-binaries]
      trigger: true
    - get: production-binaries
      passed: [lts-build-production-binaries]
    - get: production-linux-binary
      passed: [lts-build-production-binaries]
    - get: task-docker-image
    - get: ci
  - task: collect-with-opsmanager-user-creds
    image: task-docker-image
    input_mapping:
      binary: production-linux-binary
    file: ci/ci/tasks/collect.yml
    params:
      OPS_MANAGER_URL: {{production-courier-ops-manager-url}}
      OPS_MANAGER_USERNAME: {{production-courier-ops-manager-username}}
      OPS_MANAGER_PASSWORD: {{production-courier-ops-manager-password}}
      ENV_TYPE: development
      INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: {{production-courier-cf-api-url}}
      USAGE_SERVICE_URL: {{production-courier-usage-service-url}}
      USAGE_SERVICE_CLIENT_ID: {{production-courier-usage-service-client-id}}
      USAGE_SERVICE_CLIENT_SECRET: {{production-courier-usage-service-client-secret}}
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
  - task: send
    image: task-docker-image
    input_mapping:
      binary: production-linux-binary
    file: ci/ci/tasks/send.yml
    params:
      API_KEY: {{production-loader-api-key}}

- name: lts-release-to-pivnet
  plan:
  - aggregate:
    - get: aqueduct-courier
      resource: lts-aqueduct-courier
      passed: [lts-test-collect-and-send-production]
      trigger: true
    - get: production-binaries
      passed: [lts-test-collect-and-send-production]
    - get: ci
  - task: generate-version-file
    file: ci/ci/tasks/generate-version-file.yml
    params:
      VERSION: {{lts_version}}
  - task: prepare-release-files
    file: ci/ci/tasks/prep-release-files.yml
    input_mapping:
      binaries-tar: production-binaries
  - task: write-metadata
    file: ci/ci/tasks/write-metadata.yml
  - put: pivotal-telemetry-collector
    params:
      file_glob: release-files/*
      metadata_file: metadata/metadata

groups:
- name: edge
  jobs:
  - courier-tests
  - windows-courier-tests
  - build-staging-binaries
  - test-collect-credhub-info
  - test-collect-and-send
  - build-production-binaries
  - auto-patch
  - test-collect-and-send-production
  - release-to-pivnet
  - major
  - minor
  - patch
  - ensure-production-sends
- name: lts
  jobs:
  - lts-courier-tests
  - lts-windows-courier-tests
  - lts-build-staging-binaries
  - lts-test-collect-credhub-info
  - lts-test-collect-and-send
  - lts-build-production-binaries
  - lts-test-collect-and-send-production
  - lts-release-to-pivnet
