name: windows-worker

releases:
- name: concourse
  version: 4.0.1-rc.6
  url: https://s3.amazonaws.com/concourse-release-candidates/concourse-4.0.1-rc.6.tgz
  sha1: 739ff95802f9db73b89c76b14679410c624df64a
- name: windows-tools
  version: 8
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=8
  sha1: 7d025c66c65a04ca79b7c21ac8e12f8a301db036
- name: windows-utilities
  version: 0.10.0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.10.0
  sha1: 2bf15743be48e696a72236c05e8e3e137474cedd

stemcells:
- alias: windows2016
  os: windows2016
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: windows-worker
  instances: 1
  vm_type: default
  vm_extensions: [100GB_ephemeral_disk]
  stemcell: windows2016
  networks: [{name: default}]
  azs: [z1]
  jobs:
  - name: houdini-windows
    release: concourse
  - name: baggageclaim-windows
    release: concourse
  - name: worker-windows
    release: concourse
    properties:
      team: ((team))
      tsa:
        host: ((tsa_host))
        host_public_key: ((tsa_host_public_key))
        worker_key: ((worker_private_key))
  - name: golang-windows
    release: windows-tools
  - name: git
    release: windows-tools
  - name: enable_ssh
    release: windows-utilities
