name: windows-worker

releases:
- name: concourse
  version: "5.3.0"
  url: "https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=5.3.0"
  sha1: 97410a92b3c2385b728a7414ad34520491701d4e
- name: windows-tools
  version: 46
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=46
  sha1: de4369dbce21546296185103ea9a53d61f1d4c0a
- name: windows-utilities
  version: "0.11.0"
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0
  sha1: efc10ac0f4acae23637ce2c6f864d20df2e3a781

stemcells:
- alias: windows2016
  os: windows2016
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: windows-worker
  instances: 1
  vm_type: default
  vm_extensions: [100GB_ephemeral_disk]
  stemcell: windows2016
  networks: [{name: default}]
  azs: [z1]
  jobs:
  - name: worker-windows
    release: concourse
    properties:
      team: ((team))
      tsa:
        host: ((tsa_host))
        port: 2222
        registration_mode: forward
        host_public_key: ((tsa_host_public_key))
        worker_key:
          private_key: ((worker_private_key))
  - name: golang-windows
    release: windows-tools
  - name: git
    release: windows-tools
  - name: enable_ssh
    release: windows-utilities
