name: windows-worker

releases:
- name: concourse-windows-worker
  version: 3.13.0
  url: https://bosh.io/d/github.com/pivotal-cf-experimental/concourse-windows-worker-release?v=3.14.1
  sha1: 5681463f0766e786a5ea8bf12558238bf69fc8f3
- name: windows-tools
  version: 8
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=8
  sha1: 7d025c66c65a04ca79b7c21ac8e12f8a301db036
- name: windows-utilities
  version: 0.10.0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.10.0
  sha1: 2bf15743be48e696a72236c05e8e3e137474cedd

stemcells:
- alias: windows2016
  os: windows2016
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: windows-worker
  instances: 1
  vm_type: default
  vm_extensions: [50GB_ephemeral_disk]
  stemcell: windows2016
  networks: [{name: default}]
  azs: [z1]
  jobs:
  - name: concourse_windows
    release: concourse-windows-worker
    properties:
      concourse_windows:
        team: ((team))
        tsa_host: ((tsa_host))
        tsa_public_key: ((tsa_host_public_key))
        tsa_worker_private_key: ((worker_private_key))
  - name: golang-windows
    release: windows-tools
  - name: git
    release: windows-tools
  - name: enable_ssh
    release: windows-utilities
